configurable:
  user_id: "test_user"
  template_dir: "${WORKSPACE_ROOT}/integrations/common_templates"
  custom_template_dir: null
  use_isolation: false
  isolation_method: "direct"
  execution_timeout: 300
  skip_verification: false
  rule_based_optimization: true
  use_static_analysis: true
  db_connection_string: "workflow_history.db"
  prune_history_days: 90
  plugin_dirs:
    - "${WORKSPACE_ROOT}/plugins"
  max_concurrent_tasks: 5
  least_privilege_execution: true
  log_level: "DEBUG" 