# Basic settings
version: '1.0.0'
log_level: 'INFO'
log_file: 'workflow_agent.log'

# Path settings
template_dir: './templates'
script_dir: './generated_scripts'
backup_dir: './backup'

# Security settings
security:
  least_privilege_execution: true
  script_execution_timeout: 600
  use_docker_isolation: false

# Execution settings
isolation_method: 'direct'
execution_timeout: 300
max_retries: 3

# Features
use_recovery: true
skip_verification: false
