# Workflow Agent Configuration

# Logging Configuration
log_level: "DEBUG"
log_file: "workflow_agent.log"

# Integration Configuration
template_dir: "./templates"
storage_dir: "./storage"
plugin_dirs: 
  - "./plugins"

# LLM Configuration
llm_provider: "gemini"
# API keys should be set via environment variables
# OPENAI_API_KEY for OpenAI
# GEMINI_API_KEY for Google Gemini

# Execution Configuration
use_recovery: true
max_retries: 3
timeout_seconds: 300
