# Workflow Agent Configuration

# Logging Configuration
log_level: "DEBUG"
log_file: "workflow_agent.log"

# Integration Configuration
template_dir: "./templates"
storage_dir: "./storage"
plugin_dirs: 
  - "./plugins"

# LLM Configuration
llm_provider: "gemini"
gemini_api_key: ""

# Execution Configuration
use_recovery: true
max_retries: 3
timeout_seconds: 300
