# Infrastructure Agent Installation Script
# Generated by Workflow Agent

# Parameters
$LicenseKey = "{{ license_key }}"
$Host = "{{ host }}"
# Default values for missing parameters
$InstallDir = "{{ parameters.install_dir | default('C:\\Program Files\\InfraAgent') }}"
$ConfigPath = "{{ parameters.config_path | default('C:\\ProgramData\\InfraAgent\\config') }}"
$LogPath = "{{ parameters.log_path | default('C:\\ProgramData\\InfraAgent\\logs') }}"
$Port = "{{ parameters.port | default('8765') }}"

Write-Host "Starting Infrastructure Agent installation..."
Write-Host "License Key: $LicenseKey"
Write-Host "Host: $Host"
Write-Host "Install Directory: $InstallDir"
Write-Host "Config Path: $ConfigPath"
Write-Host "Log Path: $LogPath"

# Create directories
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
New-Item -ItemType Directory -Force -Path $ConfigPath | Out-Null
New-Item -ItemType Directory -Force -Path $LogPath | Out-Null

# Create configuration file
$ConfigContent = @"
{
  "license_key": "$LicenseKey",
  "host": "$Host",
  "port": "$Port",
  "log_level": "INFO",
  "log_path": "$LogPath"
}
"@

Set-Content -Path "$ConfigPath\config.json" -Value $ConfigContent

# Simulate download and installation
Write-Host "Downloading Infrastructure Agent package..."
Start-Sleep -Seconds 1
Write-Host "Downloaded Infrastructure Agent package"

Write-Host "Installing Infrastructure Agent..."
Start-Sleep -Seconds 1
Write-Host "Infrastructure Agent installed successfully"

# Report changes for tracking
Write-Host "CHANGE_JSON_BEGIN"
Write-Host @"
{
  "type": "file_create",
  "target": "$ConfigPath\\config.json",
  "revertible": true,
  "backup_file": null
}
"@
Write-Host "CHANGE_JSON_END"

Write-Host "CHANGE_JSON_BEGIN"
Write-Host @"
{
  "type": "directory_create",
  "target": "$InstallDir",
  "revertible": true,
  "backup_file": null
}
"@
Write-Host "CHANGE_JSON_END"

Write-Host "Installation completed successfully"
exit 0
