parameters:
  - name: license_key
    description: "License key for the monitoring agent"
    type: string
    required: true
    
  - name: host
    description: "Host to monitor"
    type: string
    required: true
    default: "localhost" 